#pragma once
void saveMedicineDataLocally();
void saveUserDataLocally();
void saveRequestsDataLocally();
void saveAllDataLocally();
void saveMedicineDataToArr();
void saveUserDataToArr();
void saveAllDataToArr();
void saveOneUserDataLocally();