#pragma once
void saveMedicineDataLocally();
void saveUserDataLocally();
void saveRequestsDataLocally();
void savePayMethodLocally();
void saveAllDataLocally();
void saveOrderDataLocally();
void loadMedicineDataToArr();
void loadUserDataToArr();
void loadAllDataToArr();
void loadPayMethodToVec();
void loadOrderDataToArr();
void saveOneUserDataLocally();
void saveOneMedDataLocally();