#pragma once
void saveMedicineDataLocally();
void saveUserDataLocally();
void saveRequestsDataLocally();
void savePayMethodeLocally();
void saveAllDataLocally();
void loadMedicineDataToArr();
void loadUserDataToArr();
void loadAllDataToArr();
void loadPayMethodeToVec();
void saveOneUserDataLocally();
void saveOneMedDataLocally();